name: llm596
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - transformers>=4.41.0
    - sentence-transformers>=3.4.1
    - datasets>=3.2.0
    - accelerate>=0.26.0
    - scikit-learn
    - numpy>=1.26.4
    - pandas>=2.2.2
    - tqdm>=4.67.1
    - huggingface-hub>=0.28.1
    - langchain-community
    - google-api-python-client
