name: llm596
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - tensorflow-gpu
  - numpy
  - matplotlib
  - jupyter
  - pillow
  - pip
  - pip:
    - openai 